FROM registry.access.redhat.com/ubi8/openjdk-11

WORKDIR /app

ENV CATALINA_HOME=/app/tomcat
ENV PATH="$CATALINA_HOME/bin:$PATH"

# Tomcat version hardcoded to avoid ENV inside RUN
RUN curl -fsSL https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz -o tomcat.tar.gz \
 && tar -xzf tomcat.tar.gz \
 && mv apache-tomcat-9.0.65 tomcat \
 && rm -rf tomcat.tar.gz tomcat/webapps/docs/appdev/sample

COPY target/*.war tomcat/webapps/

EXPOSE 8081

CMD ["catalina.sh", "run"]
