FROM registry.access.redhat.com/ubi8/openjdk-11

ENV TOMCAT_VERSION=9.0.65
ENV CATALINA_HOME=/app/tomcat
ENV PATH="$CATALINA_HOME/bin:$PATH"

WORKDIR /app

RUN curl -fsSL https://archive.apache.org/dist/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz -o tomcat.tar.gz \
 && tar -xzf tomcat.tar.gz \
 && mv apache-tomcat-${TOMCAT_VERSION} tomcat \
 && rm -rf tomcat.tar.gz tomcat/webapps/docs/appdev/sample

COPY target/*.war tomcat/webapps/

EXPOSE 8081
CMD ["catalina.sh", "run"]
